backend:
  name: github
  repo: eddiewebb/pairfect-strangers
  open_authoring: true

publish_mode: editorial_workflow
media_folder: "src/static/uploads" # Folder where user uploaded files should go
public_folder: "/uploads"

collections: # A list of collections the CMS should be able to edit
  - name: "Post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "src/content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: tags, widget: list }
      - {label: "languages", name: languages, widget: select, multiple: true, options: ["java","golang","python","php","js","ruby"] }
      - {label: "technologies", name: technologies, widget: select, multiple: true, options: ["java","golang","python","php","js","ruby"] }
